### ISSUE TITLE
Add some links to PeakGroup and PeakData results pages

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#176]
### Feature Inspiration

Linking across various objects in the database makes browsing data/results intuitive.

### Feature Description

PeakGroup
* Tissue => Tissue
* Enrichment Fraction, Enrichment Abundance, Normalized Labeling => PeakGroup
* Peak Group Set Filename => PeakGroupSet

PeakData
* Tissue => Tissue
* Raw Abundance, Corrected Abundance, Fraction, Median M/Z, Median RT => PeakData

### Comment

-----

### Assumptions

- List of assumptions made WRT the code
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- List of conditions to be met for the feature
- E.g. Every column/row must display a value, i.e. cannot be empty

### Limitations

- A list of things this work will specifically not do
- E.g. This feature will only handle the most frequent use case X

### Affected/Changed Components

- Files
- Environment variables
- External executables
- Database tables
- Cron job settings
- Etc.

#### GUI Change description

Describe changes the user will see.

#### Code Change Description *(Pseudocode optional)*

Describe code changes planned for the feature.

#### Tests

A test should be planned for each requirement (above), where possible.

**Comment by hepcat72** [comment]
Good thought.  Should we take that further?  Maybe clicking anywhere in a row (other than linked values) should go to that record's details page?

**Comment by lparsons** [comment]
I'm fine with whatever implementation seems to make sense. That sounds reasonable.

**Comment by hepcat72** [comment]
Assuming some of these are talking about links from advanced search to detail and/or list pages.  Creating a more specific list WRT the direction of these links...

I will assume that in these cases, the adding of these types of links are not implied:

- Advanced search results (any format) -> list pages using measured (or other non-unique field) values (e.g. raw abundance) is not implemented
- Advanced search results (any format) -> details pages using measured values (e.g. raw abundance) is not specific enough
   - In the case of the advanced search peak groups format, a peak group column does exist and already links to the peak group detail pages.
   - In the case of peak data, there is no column to link to a peak data detail page - however there is currently no template for a peak data record anyway.
- Linking of values (e.g. a tissue) on details pages to advanced search pages is not implied because the value exists in multiple formats (e.g. tissue is displayed in both peak group and peak data advanced search formats), though perhaps separate links rendered under the details or in new list columns could be added...

The following appear to already exist (if checked) or are not possible (if so indicated):

- [x] Links from the tissue values in the Advanced Search Peak Group results to tissue detail pages
- **X** Links from PeakGroup Detail pages to Advanced Search Peak Group pages for Enrichment Fraction, Enrichment Abundance, Normalized Labeling => PeakGroup
   - These are not possible the way it seems to be implied in the feature description of this issue (though I could be interpreting it wrong). The way the advanced search is implemented, you cannot search using cached properties as search terms.  That also applies to `search_basic` links to advanced search.
- [ ] Advanced Search Peak Group results' Peak Group Set Filename => PeakGroupSet Detail pages
- [x] Advanced Search Peak Data results' Peak Group Set Filename => PeakGroupSet Detail pages
- [ ] Links from tissue values in Advanced Search Peak Data results to tissue detail pages
- [ ] Peak Data details' and list values for `Raw Abundance`, `Corrected Abundance`, **_Fraction_**, `Median M/Z`, `Median RT` => PeakData Advanced Search
   - As above, a link using cached properties, such as **_`fraction`_**, to advanced search is not currently possible

**Comment by lparsons** [comment]
I still believe there is value in being able to see the individual peak data rows for a given peak group. My thought had been, when viewing a PeakGroup result table, one could get to the PeakGroup detail view (to me, the total abundance makes sense to click on, or perhaps some added row) and that the PeakGroup detail view would show the PeakData rows (it has a link now, but I think should just show the rows (#151). Other ideas on how to allow easy browsing to the PeakData for a given PeakGroup from the PeakGroup list?
