### ISSUE TITLE
Handle missing numeric values in Animal and Sample table

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#253]
@Rob if I filled with None, it changed the data type for the column. e.g if the column value is 1, it's changed to 1.0 which would mess up with hyperlink using id.

_Originally posted by @fkang-pu in https://github.com/Princeton-LSI-ResearchComputing/tracebase/pull/241#discussion_r751829283_

**Comment by hepcat72** [comment]
I don't think this is an issue per se.  This "issue" is that you cannot discern between actual 0 values and values that were missing and filled in with 0 (so that the dataframe code would work).  But Fan convinced me that you *have* to convert None to a numeric value in order for the code to work, so nothing can really be done to make None values appear as `None` unless you kept track of the none fields spearately and reverted them to "None" in the template.  But I don't think it's worth it.  My concern had been consistency with the Advanced search results display.  And I feel like a real "solution" would be to not use dataframes in the context.  We could revisit if Fan decides to implement server-side pagination to speed things up, but otherwise, I vote we close this and leave it as-is.
