### ISSUE TITLE
Allow empty values in optional animal/sample columns during loading

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#261]
### Feature Inspiration

When filling out a animal / sample table, some fields are optional. It would be nice to allow the column values to be empty if the value is optional. Currently, the column must either not exist or must be completely filled. 

### Feature Description

If an optional column exists in the data loading, (e.g. Animal Body Weight), empty values in that column should be OK and simply result in `null` values in the database.

### Alternatives Considered

A brief description of any alternative features that may accomplish the same
ultimate goal.

### Comment

An example file that exhibits this behavior is
[animals_samples_treatments.xlsx](https://github.com/Princeton-LSI-ResearchComputing/tracebase/files/7566385/animals_samples_treatments.xlsx)

```
python manage.py load_animals_and_samples --animal-and-sample-table-filename animals_samples_treatments.xlsx
```
-----

### Assumptions

- List of assumptions made WRT the code
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- List of conditions to be met for the feature
- E.g. Every column/row must display a value, i.e. cannot be empty

### Limitations

- A list of things this work will specifically not do
- E.g. This feature will only handle the most frequent use case X

### Affected/Changed Components

- Files
- Environment variables
- External executables
- Database tables
- Cron job settings
- Etc.

#### GUI Change description

Describe changes the user will see.

#### Code Change Description *(Pseudocode optional)*

Describe code changes planned for the feature.

#### Tests

A test should be planned for each requirement (above), where possible.

**Comment by hepcat72** [comment]
> Currently, the column must either not exist or must be completely filled.

This is (currently) incorrect.  I'm not sure exactly when the val_required variable was added, but it's been there for awhile.

I think this issue should be changed to specify which columns should allow the values to be optional, because the ability to require columns and values in those columns are independent, but the last I looked (during the refactor), there were only 3 columns where the values in certain columns were optional:

- tissue
- Study description
- treatment

There was a comment about the tissue, attributing it possibly being empty due to the sample being a blank.

**Comment by hepcat72** [comment]
This is done.
