### ISSUE TITLE
Define format to describe multiple tracers on Animals and Samples Sheet

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#400]
### Feature Inspiration

Experiments sometimes use multiple tracer compounds per animal. The Animal and Sample data sheet needs to be able to accomodate this information. Right now, researchers use various forms of shorthand (see #389)  to encode this, but the format is not well defined and can be ambiguous. For example, when specifying labeling for a 6 amino acid tracer combination, labeled with both Carbon and Nitrogen, the researcher simply specified six numbers (*e.g.* `4.2.5.3.3.5`). It's not clear which is associated with which amino acid nor which element(s) are labeled in each amino acid.

### Feature Description

* Describe a format that is expressive enough to capture multiple tracers and multiple labeled elements per tracer

[Current example](https://docs.google.com/spreadsheets/d/1ZO1pxuzCiJurstU7rQz78pe3SGBO48N_/edit?usp=sharing&ouid=111924602608972616243&rtpof=true&sd=true) - check the AnimalMultiTracersMultiElements sheet within the book, but dual label (C, N) of 3 amino acids was paired with only 3 labeled ion count (Nitrogen perhaps all assumed to be 1)

# Proposal

## Tracer 
There with be a single ~~`Tracer`~~ `Infusate` column that encodes/replaces the existing template `Tracer Compound`,`Tracer Labeled Element` &`Tracer Label Atom Count`. `Infusion Rate` remains unchanged.

* Individual tracer compounds will be formatted: `compound_name`-[`weight` `element` `count`,`weight` `element` `count`]
    examples:
    * valine-[13C5,15N1]
    * leucine-[13C6,15N1]
    * isoleucine-[13C6,15N1]
* If a tracer is not fully labeled for a given element, the positions of the that element must be included: `compound_name`-[`position`,`position`-`weight` `element` `count`]
    example:
    * L-Leucine-[1,2-13C2]
* Mixtures of compounds will be formatted: `tracer_mix_name` `{tracer; tracer}`. `tracer_mix_name` is optional
    Examples:
    * BCAAs {isoleucine-[13C6,15N1];leucine-[13C6,15N1];valine-[13C5,15N1]}
    * isoleucine-[13C6,15N1];leucine-[13C6,15N1];valine-[13C5,15N1]

## Tracer Concentration

The ~~`Tracer Concentration`~~ `Tracer Concentrations` column remains (pluralized), and if it is a complex mixture, it contains a semi-colon delimited list of floats, in the **_same order and cardinality_** as the list as semi-colon delimited tracer encodings in the  proposed `Tracer` column.

### Alternatives Considered
See questions and comments, below...

### Comment

Before finalizing the format, it must be reviewed with researchers to ensure they find it workable.

**NOTE:** Updated template is here (will eventually replace old template) - https://docs.google.com/spreadsheets/d/1ywj9BvwX76ygRc5iXHwmzBcg1CWc5eFjLGOC6NtSHo8/edit?usp=sharing

-----

### Assumptions

- regex pattern the bracket-encoded tracer encoding for approx. `(13C)(\d+)` and `(15N)(\d+)` for tracer element and count.
- store intact/encoded individual tracer in tracer.name
- store alphabetically sorted encoded tracer list in tracer_group.name
- store optional mix name ("6EAAs") in tracer_group.preferred_name
- lists of tracer encodings and concentration are semi-colon delimited
- the compound name in a tracer encoding **must exist** in either `compound` table or `compound_synonym`

### Requirements

- Cocktails of isotope labeled tracers (multiple compounds)
- Multiple isotopes per tracer (13C, 15N)

### Limitations

- A list of things this work will specifically not do
- E.g. This feature will only handle the most frequent use case X

### Affected/Changed Components

- [Sample Animal template](https://docs.google.com/spreadsheets/d/1To3495KxJkAtnAD9KVdzc162zKbNiYuPEVyPseQPjMQ/copy), potentially
- implies changes to parsing and loading samples/animals

#### GUI Change description

Describe changes the user will see.

#### Code Change Description *(Pseudocode optional)*

Describe code changes planned for the feature.

#### Tests

A test should be planned for each requirement (above), where possible.

**Comment by lparsons** [comment]
Here is the current proposal from the lab: https://github.com/Princeton-LSI-ResearchComputing/tracebase/pull/389#discussion_r819952659:

> Tracer group specification format:
> * tracer compound = `BCAAs {valine, leucine, isoleucine}`
> * tracer labeled element = `C, C, C` (each tracer compound has carbon labeled)
> * tracer labeled element count = `5, 6, 6` (valine has 5, leucine 6, isoleucine 6)
> * tracer concentration = `80, 100, 60` (each tracer compound has its own concentration

**Comment by mneinast** [comment]
>1. Are any infused tracers not 100% labeled for the targeted element(s)?

Yes, sometimes only a subset of atoms in the tracer are labeled.  `Whole-body PPP` is an example where only two of the carbons in glucose are labeled.

>2. Are there any existing naming conventions that could be used to communicate the isotope element and counts?

None are reliably adhered to in the lab right now, but I think the best option is `L-Glutamine-[13C5,15N2]` because this is like the format used by most suppliers of the tracer.  See [example from cambridge isotopes](https://shop.isotope.com/productdetails.aspx?itemno=CLM-116-PK)

>Given the above, would need to be able to communicate a list of tracers

Yes and I can see how this would get a little complicated.  For example:  `BCAAs {valine-[13C5,15N1], leucine-[13C6,15N1], isoleucine-[13C6,15N1]}` (perhaps using semicolon instead of comma).

An additional problem with the named tracer list is that `BCAAs` could mean various combinations of labeled elements.  We would have to keep track on the tracebase side or come up with a standardized way to track this, or perhaps we can ignore the user supplied name of the tracer group and instead derive our own?

**Comment by jcmatese** [comment]
@lparsons @hepcat72 @fkang-pu @mneinast One thing to be considered (since this template proposal predated the model proposal discussed this week, including `Infusate`) is whether `Tracer` and `Tracer Concentration` should remain labeled so [and everyone knows what is truly inside those columns and how they are mapped], or whether they _might_ be better labeled `Infusate` and `Infusate Concentrations` (or similar).

**Comment by hepcat72** [comment]
I think that part of the effort to allow multiple tracers correctly separates Tracer from being a 1:1 with infusate to a M:1, which means that "infusate" as a term now represents the mixture.  And each tracer has its own concentration in that solution.  I.e., we're not doing multiple infusions into the mouse.  We're doing 1 infusion and the infusate includes N tracers, each at a specific concentration.  I in fact think it would be confusion to apply the term infusate to each tracer and each tracer's concentrations, because that, to me, does not truly represent the relationships.  But I think it's good that we consider potential user confusion, so I would like to know if the researchers apply the term "infusate" to the mixture or each individual tracer. If there are differing opinions, we would definitely need something to address it.

**Comment by lparsons** [comment]
> I think that part of the effort to allow multiple tracers correctly separates Tracer from being a 1:1 with infusate to a M:1, which means that "infusate" as a term now represents the mixture. And each tracer has its own concentration in that solution.

Exactly, the software (TraceBase) is now making a clear distinction in how it uses those terms. It's probably good to be as consistent about those as we can, esp. when we are communicating ideas. However, it's important that we understand that researchers may not be as precise with the language (and may not even define things similarly), so when we intake data, we should be as forgiving and relaxed as is reasonable. That said, I think making the default column headers `Infusate` and `Infusate Concentrations` makes a lot of sense. We have the flexibility to map those to different headings if the researcher uses other terms. As long as the data is in the proper format, we can interpret the headings.

**Comment by jcmatese** [comment]
Zoom discussion with @lparsons  and @hepcat72  decided the the columns should be `Infusate`  and `Tracer Concentrations` [rather than the original proposal `Tracer` and `Tracer Concentration` ].  This final decision was made to indicate the concept of _multiple_ tracers (and corresponding concentrations) in the infusion process/cocktail.

**Comment by hepcat72** [comment]
Wait, I thought "Infusate" was to be for "Tracer Group".  I wouldn't think that the "Tracer" column should be named "Infusate". But like I said, I'm not married to my suggestion. I just think we shouldn't use infusate differently in different contexts. @lparsons @jcmatese

**Comment by lparsons** [comment]
This has been decided now, and the issue for implementation is #407.

**Comment by hepcat72** [comment]
In our last meeting on this, remember a discussion on using commas to delimit 2 different kinds of data.  I'm guessing that it was the position delimiting and the label-delimiting, but since the given examples in the proposals above don't include that case, I thought I'd double-check that it wasn't in regard to the tracer-delimiting (which the format shows using semicolons).

So, to extend one of the examples, it this correct?:

`BCAAs {isoleucine-[1,2-13C6,15N1];leucine-[13C6,15N1];valine-[3,4,5-13C5,15N1]}`

@jcmatese

**Comment by jcmatese** [comment]
> So, to extend one of the examples, it this correct?:
> 
> `BCAAs {isoleucine-[1,2-13C6,15N1];leucine-[13C6,15N1];valine-[3,4,5-13C5,15N1]}`

I thought that would be 
`BCAAs {isoleucine-[1,2-13C2,15N1];leucine-[13C6,15N1];valine-[3,4,5-13C3,15N1]}`

i.e. if the ArrayField is `1,2` (length==2) then it should be 13C**2** or if `3,4,5` then 13C**3**

**Comment by hepcat72** [comment]
I thought we decided in the last meeting about this that positions were optional - that you didn't have to have all positions. Didn't Michael chime in on that in that in-person meeting?

But I was asking about the semicolon delimiter. I thought you wanted it to be a comma based on a chemical db site's standard.

**Comment by jcmatese** [comment]
No, I would prefer it to be left as semi-colon, because semi-colons are **NOT** generally used in chemical names, where as **commas are fairly commonplace**.  Unless someone has a better delimiter that the lab members prefer...

I don't feel too strongly about the isotope-count postscript. [if absent, assume fully labeled based on formula, else respect the `integerArrayField` count ].  Whatever the lab members want, because although it is explicit, it _is_ kind of redundant, and I would not claim it necessarily is widespread/common, though I have seen it for fully labeled molecules 

Examples
[L-Leucine-13C6,15N](https://www.sigmaaldrich.com/US/en/product/aldrich/608068) - postscript on carbon, but not the nitrogen (1 is assumed, by convention).  _Synonym lacks postscripts_
[L-Alanine-13C3,15N](https://www.sigmaaldrich.com/US/en/product/aldrich/489883)- postscript on carbon, but not the nitrogen  (1 is assumed, by convention)

Ideally, we wold try to closely approximate the nomenclature from whatever catalog they are ordering from, but I never saw that spreadsheet or a suggestion of a preferred vendor.

**Comment by hepcat72** [comment]
Since I'm working on #430, I'm going to assume that the discrepancy between the description of the concentrations column in the [revised template](https://docs.google.com/spreadsheets/d/1ywj9BvwX76ygRc5iXHwmzBcg1CWc5eFjLGOC6NtSHo8/edit?usp=sharing):

> [...] Multiple tracers in a single infusion should have concentrations specified as **comma** separated lists.

...and the description in the issue:

> ## Tracer Concentration
> 
> The [...] `Tracer Concentrations` column [...] contains a **semi-colon** delimited list of floats, in the _same order and cardinality_ as the list as semi-colon delimited tracer encodings in the  proposed `Tracer` column.

Not sure which is the more recent update to that column, but I will go with semicolon.  Thus, I will modify the description of that column in the template.
