### ISSUE TITLE
Design option: how to manage auto-update for Infusate.name, Tracer.name, TracerLabel.name

### ISSUE THREAD

**Issue by fkang-pu** [Princeton-LSI-ResearchComputing/tracebase#586]
During reviewing [PR570](https://github.com/Princeton-LSI-ResearchComputing/tracebase/pull/570), a few tests were run to understand how infusate.get_name and tracer.get_name to trigger auto-update process. Share the details of the tests here to promote discussions about how to handle auto-update and when to use `get_name` methods. The following tests also related to [PR 569](https://github.com/Princeton-LSI-ResearchComputing/tracebase/pull/569).

- test design:
  Generate test cases quickly to test auto-update triggered by two methods:
  - infusate.get_name
  - tracer.get_name
  
 Note:
 The following steps will not affect the "tracebase" used for other development work. Can switch back to tracebase by editing .env file. You can also review the test input and output if you don't want to repeat the tests (skip steps 1-5). 
 
- steps to set up a quick test

   1.  create an new PosgreSQL database named "t1_auto_update"
   2. edit .env to point database to "t1_auto_update"
      line:  "DATABASE_NAME=treacebase"
      replaced with "DATABASE_NAME=t1_auto_upd"
   3. run migration:
      python manage.py migrate
   4. create cache table:
      python manage.py createcachetable
   5. load a small dataset for testing 
       loading data:
       python manage.py load_study DataRepo/example_data/test_dataframes/loading.yaml

      expected total rows:
      studies: 2 rows
      animals: 4 rows
      infusates: 4 rows
     tracers: 10 rows

6. test auto-update triggered by Infusate.get_name or Tracer.get_name

   You can download the [html file](https://drive.google.com/file/d/1LSL-b64L2r4HJxpL-2cXs4HXQNwBrCSq/view?usp=share_link) to review input and output of two tests. The output format got messed up if I tried to copied here directly.
   
   I only listed the code of test 1 below:

  - Test 1
    - input
    ```
    from DataRepo.models import *
    print("# Test 1: trigger auto-update by calling Infusate.get_name")
    print("# selected records for infusate.id=1 and tracer.id=1 for infusate.name=lysine-[13C6][15]")
    print("# make sure to set infusate.id and tracer.id correctly for selected records")
    print("# set t1_infusate_id=1 and t1_tracer_id=1 for the following tests")
    t1_infusate_id=1
    t1_tracer_id=1
    print("# make sure the name values are as expected before a new test...")
    upd_tracerlabel = TracerLabel.objects.filter(tracer_id=t1_tracer_id).update(name="13C6")
    upd_tracer = Tracer.objects.filter(id=t1_tracer_id).update(name="lysine-[13C6]")
    upd_infusate = Infusate.objects.filter(id=t1_infusate_id).update(name="lysine-[13C6][15]")
    print("# before updating selected records:")
    print("TracerLabel row:", TracerLabel.objects.filter(tracer_id=t1_tracer_id).values())
    print("Tracer row:", Tracer.objects.filter(id=t1_tracer_id).values())
    print("Infusate row:", Infusate.objects.filter(id=t1_infusate_id))
    print("# update Infusate.name, Tracer.name, TracerLabel.name to None for selected records")
    upd_tracerlabel = TracerLabel.objects.filter(tracer_id=t1_tracer_id).update(name=None)
    upd_tracer = Tracer.objects.filter(id=t1_tracer_id).update(name=None)
    upd_infusate = Infusate.objects.filter(id=t1_infusate_id).update(name=None)
    print("# after updating selected records:")
    print("TracerLabel row:", TracerLabel.objects.filter(tracer_id=t1_tracer_id).values())
    print("Tracer row:", Tracer.objects.filter(id=t1_tracer_id).values())
    print("Infusate row:", Infusate.objects.filter(id=t1_infusate_id).values())
    print("# test auto_upadte with Infusate.get_name method...")
    infusate_null_qs = Infusate.objects.filter(name__isnull=True)
    print("total rows with infusate.name is null before calling get_name:", infusate_null_qs.count())
       for i in infusate_null_qs:
           print("name value before calling get_name:", i.name)
           i.get_name
          print("name value after calling get_name method:", i.name)
    infusate_null_qs = Infusate.objects.filter(name__isnull=True)   
    print("total rows with infusate.name is null after calling get_name:", infusate_null_qs.count())
    print("# selected records after calling infusate.get_name:")
    print("TracerLabel row:", TracerLabel.objects.filter(tracer_id=t1_tracer_id).values())
    print("Tracer row:", Tracer.objects.filter(id=t1_tracer_id).values())
    print("Infusate row:", Infusate.objects.filter(id=t1_infusate_id).values())

Test Summary:

- call infusate.get_name will trigger auto-update to update Infusate.name for the instance
- call tracer.get_name will trigger auto-update to update Tracer.name for the instance and any Infusate.name linked to the tracer.
- Additional note: for "disable_buffering" case, Infusate.name, Tracer.name, TracerLabel.name are all null. Need a solution to auto-update TracerLabel.name too. 
- It's better to have a method to maintain name value for these three models after data loading, and with the option of input tracer_list. 
```

**Comment by hepcat72** [comment]
IMO, this is all worked out @fkang-pu.  I do not understand the purpose of this issue other than to help understand what we have and when to use `*.get_<field_name>`.  So let me see if I can help elucidate things...

Regarding: "Need a solution to auto-update TracerLabel.name too"...

Yes, if `TracerLabel.name` is used in queries, then having calls to `TracerLabel.get_name` would mitigate issues where those queries don't return what we want, however:

Using `get_name` isn't intended to be a "fix".  It's intended as a "mitigation" and a "warning" that something is wrong.  It does what it can to provide the user with correct information if a problem is found during the display of a field value, and mitigates issues surrounding the querying of those fields.  When it is used, it fills in the correct value if the associated field is `None`, saves it, propagates that change to the associated fields, and reports a warning in the log (at least, that's what's done in the pending  PR #569 - I don't recall what the hard-coded get_name methods do ATM).  And it so happens that the propagation direction is `TracerLabel.name` -> `Tracer.name` -> `Infusate.name`.  That is defined in the decorators on the associated `_name` functions.  Thus, if you call `tracer_object.get_name`, it updates `tracer_object.name` and `tracer_object.infusates.name`.  It fills in the correct TracerLabel name because it uses it's `TracerLabel._name` method, but that value is not saved, and it shouldn't save it.

The intended outcome is: we're alerted that null values have been found and that prompts us to fix associated fields like `TracerLabel.name` on the back-end.  We don't expect these values to be null, and I think that engineering the automated code to completely solve that problem is (at the risk of insulting myself) over-engineering the issue.

**ALL** we need to do when considering whether to use `*.get_<field_name>` is use it if we ever want to **use** the field returned from a query.  The only thing a query can do is use the actual field, because `get_<field_name>` doesn't exist in the database.  Queries use the actual field, but what we do with the query results is use the **getter** to retrieve the value from the **object**.

**Comment by hepcat72** [comment]
`get_name` is going to go away.  This functionality has been built into `MaintainedModel` and is obfuscated from explicit usage.
