### ISSUE TITLE
Allow AccuCor files to load peak data even if tracer contains multiple labeled elements

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#656]
### Problem

This may not be a "bug" technically,  but this template seemed useful.

When attempting to load an Accucor file that contains samples taken from animal that was infused with a tracer that contained more than one labeled element (*e.g.* `13C` and `15N`), an exception is thrown.

### Steps to reproduce

1. Attempt to load the attached study [issue-multilabled-tracer-accucor-load.zip](https://github.com/Princeton-LSI-ResearchComputing/tracebase/files/10913134/issue-multilabled-tracer-accucor-load.zip)

#### Base conditions
- Tracer contains multiple labels
- Loading an AccuCor file
- AccuCor file contains data for only a single labeled element in every row (should be the case for unaltered AccuCor output)

#### Cases
1. Detected compound contains more than one of the labeled elements
2. Detected compound contains only one of the labeled elements

### Current behavior

Exception: 
```
InvalidNumberOfLabeledElements: This code only supports a single labeled element in the original data sheet. Row 1 has 2.
```

### Expected behavior

- Case 1 - Warning
- Case 2 - No warning

Alternative behavior
- Case 1 and Case 2 generate a Warning

### Comment

-----

### Assumptions

- List of assumptions made WRT the code
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- [ ] 1. List of numbered conditions to be met for the feature
- [ ] 2. E.g. Every column/row must display a value, i.e. cannot be empty
- [ ] 3. Numbers for reference & checkboxes for progress tracking

### Limitations

- A list of things this work will specifically not do
- E.g. This feature will only handle the most frequent use case X

### Affected Components

A list of repository items, dependencies, etc, labeled with add, delete, or
change.  One item per line.  (Mostly, this will be a list of files.)

- change: File path or DB table ...
- add: Environment variable or server setting
- delete: External executable or cron job

#### GUI Change description

Describe changes the user will see.

#### Code Change Description

Describe code changes planned for the feature. *(Pseudocode encouraged)*

#### Tests

- [ ] 1. A description of at least one test for each requirement above.
- [ ] 2. E.g. Test for req 2 that there's an exception when display value is ''
- [ ] 3. Numbers for reference & checkboxes for progress tracking

**Comment by hepcat72** [comment]
This code is behaving as it was originally designed.  The outcome is intentional.  It is because I had noted during the isocorr refactor that (as indicated in this comment above where the exception is raised):

```
# Ensuing code assumes a single labeled element in the tracer(s), so raise an exception if
# that's not true
```

That assumption was inherent in the code of the first version of the accucor loader.  I believe it only grabbed the first and did not look at or parse the second (though I would have to dig into the code to confirm that's the assumption the code was making).

I definitely noted that the behavior would have not been as expected in this case, which is why I both decided to implement a separate code block(s) and added the check and the exception to the original accucor code.  I could have called it a bug at that point, but instead just decided to implement a known limitation of the code.

Point being, that makes this issue a `feature request`.  But I'll leave it as a bug, since that was my initial interpretation when I added the exception.  I probably should have created an issue, but I didn't know that having more than 1 labeled elements in an accucor file could have been intentional/correct.
