### ISSUE TITLE
Create `LCMethod` model class

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#702]
### Inspiration

The `LCMethod` model class will store basic information about the liquid chromatography method that is intended to convey rough equivalency between runs. The goal is to be less precise with the intention of remaining accurate and useful.

Part of the [TraceBase MS Data Storage Model](https://docs.google.com/document/d/1CUg1fChG3ZEHgMcLZnzq5eRDxiixhhH5quELHXjLIRc/edit?usp=sharing)

### Description

Create a model class `LCMethod` with the following fields:
* `id` PK int
* `chromatographic_technique` enum UNIQUE
* `run_length` int UNIQUE
* `description` string NULL

![image](https://github.com/Princeton-LSI-ResearchComputing/tracebase/assets/645128/5df95018-e63d-4a61-9812-1a1641e4fc23)

### Comment

-----

### Assumptions

- List of assumptions that the code will not explicitly address/check
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- [ ] 1. List of numbered conditions to be met for the feature
- [ ] 2. E.g. Every column/row must display a value, i.e. cannot be empty
- [ ] 3. Numbers for reference & checkboxes for progress tracking

### Limitations

- A list of things this work will specifically not do
- E.g. This feature will only handle the most frequent use case X

### Affected Components

A tentative list of anticipated repository items that will be changed, labeled
with "add", "delete", or "change".  One item per line.  (Mostly, this will be a
list of files.)

- change: File path or DB table ...
- add: Environment variable or server setting
- delete: External executable or cron job

#### Interface Change description

Describe changes to usage. *E.g. GUI/command-line changes*

#### Code Change Description

Describe code changes planned for the feature. *(Pseudocode encouraged)*

#### Tests

- [ ] 1. A description of at least one test for each requirement above.
- [ ] 2. E.g. Test for req 2 that there's an exception when display value is ''
- [ ] 3. Numbers for reference & checkboxes for progress tracking

**Comment by jcmatese** [comment]
Q: Are the enumerated `LCMethod.chomatographic_technique`'s encoded in the model, or is there going to be a `cv_term` or  `cv_enum` class ([example](https://htseq.princeton.edu/cgi-bin/tools/viewSchema.pl?table=CV_ENUM)) .  

I am assuming the former, but I don't know if I have seen a comprehensive enumerated list floating around, beyond the google study submission form's references.

**Comment by lparsons** [comment]
> Q: Are the enumerated `LCMethod.chomatographic_technique`'s encoded in the model, or is there going to be a `cv_term` or `cv_enum` class ([example](https://htseq.princeton.edu/cgi-bin/tools/viewSchema.pl?table=CV_ENUM)) .
> 
> I am assuming the former, but I don't know if I have seen a comprehensive enumerated list floating around, beyond the google study submission form's references.

That can certainly be part of the design proposal, but I think including it as a [Django `choices` type field](https://docs.djangoproject.com/en/4.2/ref/models/fields/#field-choices) will work well. I don't think we have a very solid list, but I can provide a starter list that we can run by @mneinast for confirmation.

These are the ones I've run across in previous work (clearly need some descriptions at least):
* `E`
* `E-waters`
* `Hilic`

**Comment by mneinast** [comment]
General types of LC methods used include:

- HILIC
- Reverse Phase

There may be others but these cover the vast majority.

**Comment by lparsons** [comment]
So, to be clear, we'll have two types of chromatographic techniques: `HILIC` and `Reverse Phase`. Should we include a third `Other` option that we can use to get data loaded and then fix later? Or do we think it would be better to hold up data loading until we figure out and add the appropriate specific technique?

**Comment by jcmatese** [comment]
Perhaps the Rabinowitz lab can provide their list of enumerated `chromatographic_techniques` at their next lab meeting?

I searched a little, and came up with a [couple](https://purl.bioontology.org/ontology/MI?conceptid=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMI_0091) of [attempts](https://purl.bioontology.org/ontology/PLOSTHES?conceptid=http%3A%2F%2Flocalhost%2Fplosthes.2017-1%23859) to define the vocabulary/space , and a [manuscript complaining about attempts to use them](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4423578/), in practice 😉 . 

Since this is built for the Rabinowitz Lab, and I don't see [Metabolights](https://www.ebi.ac.uk/metabolights/) providing a definitive "chromatography" list (that I could find, anyway), I would be fine with a simple list of terms branded with the lab's "seal-of-approval" .

**Comment by mneinast** [comment]
Yes I think we'd be fine to include our own lab's list of 2 + "other".  There true variability in the field is huge, but each individual lab is unlikely to use more than a few types of chromatography.

**Comment by jcmatese** [comment]
@mneinast @lparsons `run_length` is an integer number of minutes the a MS-sequence takes to complete (or is it each sample in the sequence)?  I suppose these questions/refinements could just come up during review...

**Comment by lparsons** [comment]
My understanding is that `run_length` is the length of time the machine runs, in minutes, _e.g._ HILIC-25min method. However, it might be best to make this a time duration field. They are a bit more work to keep track of, but it would allow a lot more flexibility of people start to use partial minutes. The default display should probably be in minutes though.

**Comment by mneinast** [comment]
Yes this should reflect length of time the machine runs.

In the back of my mind, I’m still thinking about allowing users to just
upload method files directly…could be a way to store now, figure out later.

**Comment by jcmatese** [comment]
Just for reference/example, this is an example published method, and I have emphasized the 2 attributes/strings we are targetting/extracting.

"Metabolites were analyzed using a Vanquish Horizon UHPLC System (Thermo Scientific) coupled to an Orbitrap Exploris 480 mass spectrometer (Thermo Scientific). Waters XBridge BEH Amide XP Column [particle size, 2.5 μm; 150 mm (length) × 2.1 mm (i.d.)] was used for hydrophilic interaction chromatography (**HILIC**) separation. Column temperature was kept at 25 °C. Mobile phases A = 20 mM ammonium acetate and 22.5 mM ammonium hydroxide in 95:5 (v/v) water:acetonitrile (pH 9.45) and B = 100% acetonitrile were used for both ESI positive and negative modes. The linear gradient eluted from 90% B (0.0 to 2.0 min), 90% B to 75% B (2.0 to 3.0 min), 75% B (3.0 to 7.0 min), 75% B to 70% B (7.0 to 8.0 min), 70% B (8.0 to 9.0 min), 70% B to 50% B (9.0 to 10.0 min), 50% B (10.0 to 12.0 min), 50% B to 25% B (12.0 to 13.0 min), 25% B (13.0 to 14.0 min), 25% B to 0.5% B (14.0 to 16.0 min), 0.5% B (16.0 to **20.5 min**), then stayed at 90% B for **4.5 min**. The flow rate was 0.15 mL/min."

and that is how we end up with "HILIC-25 minutes" (`chromatographic_type`-`run_length`), with presumably the above paragraph as a description.

**Comment by hepcat72** [comment]
> Summarizing the discussion in today's group meeting:
> 
> 1. The consensus was that since the purpose of this table was to be able to compare/distinguish LC-methodologies within TraceBase, and to reduce protocol drift within the lab.  Therefore, we would not creating a new `LCMethod` on-the-fly (when loading studies), but rather would be retrieving only from a list of lab-approved/enumerated methods.
> 2. Because the lab/curators are enumerating the list of LCMethods beforehand:
> 
> * all enumerated methods could be coded in a curator-created [fixture](https://docs.djangoproject.com/en/3.2/howto/initial-data/#providing-data-with-fixtures)
> * because they are coded in a fixture, we don't specifically need to enumerate the `chromatographic_type`s, beforehand, at the database or model level.
> * if we _**truly**_ don't know the `LCMethod` (historic data, only?), there could be a dedicated record for that (`chromatographic_type`=="unknown", run_length==`Null`, description, as appropriate).  Therefore, `run_length` should be nullable, unless you wanted `MSRunSequence` to have a nullable foreign key to  `LCMethod`.
> * certainly, the combination of `chromatographic_type`+`run_length`+`description` should be unique (database constraint), but as a business rule the first time a curator loads a LCMethod into the fixture that differs from a pre-existing LCMethod by _only_ the free-text description, we should re-visit this model and add attributes or perhaps a unique name (how would this "HILIC-25 v2 differ HILIC-25 v1").  So we _might_ want to make `chromatographic_type`+`run_length` unique?
> 
> Let me know if that tracks with your memory of the meeting @lparsons , @fkang-pu , and everyone (+ @hepcat72 , @mneinast ) can comment on this potential modification to the issue and eventual implementation.

I will comment on this (by editing this comment) in a bit. Replying to remind myself...

**Comment by jcmatese** [comment]
> 
> Interesting. So let me see if I understand this. Eluent component `B` (acetonitrile) is at 0.5% at minute 16 and remains at 0.5% until minute 20.5. Then it's ramped immediately up to 90% for the remaining 4.5 minutes?
> 
> There are a lot of adjustments made to the eluent throughout the entire column run. Is one of those periods of time the "variable" one that differs from HILIC to HILIC?

I cannot give the answer to that ("one", *"the* variable"), but I imagine all of the following could differ between multiple protocols sharing a type of "HILIC" (speaking of the "wide world", here).

1. The column dimensions, and the `stationary phase` it is packed with (some commercial silica beads product, potentially modified with surface/functional groups)
2. The chemical composition and concentrations of `mobile phases` A and B
3. The ratios, timespans, and number of phases of A:B during column elution.

There is no single variable, and I don't know which parameters(s) varies, in-practice, among the Rabinowitz lab members.  If I had to guess,  they are more likely varying elution strategies (2,3), rather than the column characteristics (1, stationary), but that is just a guess.

**Comment by hepcat72** [comment]
> > Interesting. So let me see if I understand this. Eluent component `B` (acetonitrile) is at 0.5% at minute 16 and remains at 0.5% until minute 20.5. Then it's ramped immediately up to 90% for the remaining 4.5 minutes?
> > There are a lot of adjustments made to the eluent throughout the entire column run. Is one of those periods of time the "variable" one that differs from HILIC to HILIC?
> 
> I cannot give the answer to that ("one", _"the_ variable"), but I imagine all of the following could differ between multiple protocols sharing a type of "HILIC" (speaking of the "wide world", here).
> 
> 1. The column dimensions, and the `stationary phase` it is packed with (some commercial silica beads product, potentially modified with surface/functional groups)
> 2. The chemical composition and concentrations of `mobile phases` A and B
> 3. The ratios, timespans, and number of phases of A:B during column elution.
> 
> There is no single variable, and I don't know which parameters(s) varies, in-practice, among the Rabinowitz lab members. If I had to guess, they are more likely varying elution strategies (2,3), rather than the column characteristics (1, stationary), but that is just a guess.

Yes. this has been my assessment as well.  I was honestly a bit surprised that it was asserted that technique and run length were [part of the "method definition" and that run length should thus not be in a separate table](https://github.com/Princeton-LSI-ResearchComputing/tracebase/pull/717#discussion_r1276741266). This puts me back into thinking [my previously stated concern](https://github.com/Princeton-LSI-ResearchComputing/tracebase/pull/717#discussion_r1276638402) about the data relationship not capturing significant differences that would make it a "different method", i.e. there could be multiple `hilic25`s.  You're right - it's a method **type**, not a method **definition**.  That's why I think we need the version number field you proposed.

Thanks for clarifying this.  I had assumed that the technique and run length were intended to be uniquely distinctive, which is why I also assumed that there was perhaps 2 phase in the run that varied in length.  If that's not the case, then I feel like another field to distinguish different methods with the same technique and run length, is necessary.

**Comment by lparsons** [comment]
Perhaps naming the class something "LCMethodType" or "LCMethodFamily" would be clearer. I'm not convinced that adding another field is necessary. If a additional methods are required, I would propose that they use a new string for  chromatographic technique. Could be as simple as "HILIC_V2" or more descriptive like "HILIC-WIDE-COLUMN".

**Comment by hepcat72** [comment]
We agree that additional data is (potentially/eventually) needed, it's just how to store it we disagree on. Perhaps if I understood what your reasoning is for why putting multiple pieces of data into 1 field is preferable to storing them in separate fields, I could find my way to agreeing.

So let me explain my reasoning for them being separate. In my opinion, these are all different pieces of data, which means they should each have their own field.  I don't see why we wouldn't have separate fields for them.  It's easier to search, involves very little code, and would be amenable to expansion, say if we were to decide in the future to scale up our data tracking of the method.  I don't see the downside.  We dealt with teasing apart overloaded fields in our databases at Los Alamos in the past and I was surprised how many variations would get into the database, but I suppose we're in control of the data here, since it would be in a fixture, so we wouldn't have to worry about things like `hilic_25m` versus `25m_hilic` being entered.

The only thinking I imagine you might have about 1 field versus 2 is less screen space and less useless data to display, but in each of those cases, that can be solved by the template.  We can display the values in a single column and opt to omit the "default 1" when present. And in the search interface, since it's an enum, it would be a select list, so user's wouldn't be able to enter a merged search term based on what they observe in the display.
